export type ReviewStatus = "Visible" | "Hidden"

export interface ReviewHistoryItem {
  action: string
  date: string
  time: string
  by: string
}

export interface ReviewItem {
  id: string
  customerId: string
  customerName: string
  customerEmail: string
  customerPhone: string
  vendorId: string
  vendorName: string
  vendorOwner: string
  rating: 1 | 2 | 3 | 4 | 5
  reviewText: string
  date: string
  time: string
  bookingId: string
  service: string
  status: ReviewStatus
  helpful: number
  notHelpful: number
  flagged: boolean
  adminNotes: string
  history: ReviewHistoryItem[]
}

export const initialReviews: ReviewItem[] = [
  {
    id: "REV-001",
    customerId: "C-2024-001",
    customerName: "Sarah Okonkwo",
    customerEmail: "sarah.okonkwo@email.com",
    customerPhone: "+234 803 456 7890",
    vendorId: "V-2024",
    vendorName: "Ubuntu Beauty Lounge",
    vendorOwner: "Amara Johnson",
    rating: 5,
    reviewText: "Absolutely amazing experience! The staff was professional and the braiding work was impeccable. Highly recommend!",
    date: "2025-11-25",
    time: "2:30 PM",
    bookingId: "BK-001",
    service: "Box Braids",
    status: "Visible",
    helpful: 24,
    notHelpful: 2,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-25", time: "2:30 PM", by: "Sarah Okonkwo" }],
  },
  {
    id: "REV-002",
    customerId: "C-2024-015",
    customerName: "Michael Adebayo",
    customerEmail: "michael.a@email.com",
    customerPhone: "+234 901 234 5678",
    vendorId: "V-2026",
    vendorName: "Chef Aisha's Kitchen",
    vendorOwner: "Aisha Abdullahi",
    rating: 4,
    reviewText: "Great food and presentation! The only reason for 4 stars is that delivery was slightly delayed, but the quality made up for it.",
    date: "2025-11-24",
    time: "6:15 PM",
    bookingId: "BK-045",
    service: "Wedding Catering",
    status: "Visible",
    helpful: 18,
    notHelpful: 1,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-24", time: "6:15 PM", by: "Michael Adebayo" }],
  },
  {
    id: "REV-003",
    customerId: "C-2024-032",
    customerName: "Grace Mwangi",
    customerEmail: "grace.m@email.com",
    customerPhone: "+254 712 345 678",
    vendorId: "V-2023",
    vendorName: "Serengeti Cafe",
    vendorOwner: "David Kimani",
    rating: 5,
    reviewText: "Best coffee in Nairobi! The ambiance is perfect for work meetings and the pastries are fresh daily.",
    date: "2025-11-23",
    time: "10:45 AM",
    bookingId: "BK-089",
    service: "Private Event Catering",
    status: "Visible",
    helpful: 31,
    notHelpful: 0,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-23", time: "10:45 AM", by: "Grace Mwangi" }],
  },
  {
    id: "REV-004",
    customerId: "C-2024-008",
    customerName: "David Chen",
    customerEmail: "david.chen@email.com",
    customerPhone: "+234 802 123 4567",
    vendorId: "V-2027",
    vendorName: "Fade District",
    vendorOwner: "Chukwudi Okonkwo",
    rating: 2,
    reviewText: "Very disappointed. The barber was 30 minutes late and the haircut was not what I asked for. Won't be returning.",
    date: "2025-11-22",
    time: "4:20 PM",
    bookingId: "BK-112",
    service: "Premium Haircut",
    status: "Hidden",
    helpful: 8,
    notHelpful: 15,
    flagged: true,
    adminNotes: "Hidden due to vendor complaint. Vendor provided evidence of service completion and customer satisfaction at the time.",
    history: [
      { action: "Review Posted", date: "2025-11-22", time: "4:20 PM", by: "David Chen" },
      { action: "Review Flagged", date: "2025-11-23", time: "9:00 AM", by: "Vendor" },
      { action: "Review Hidden", date: "2025-11-23", time: "11:30 AM", by: "Admin User" },
    ],
  },
  {
    id: "REV-005",
    customerId: "C-2024-021",
    customerName: "Amina Hassan",
    customerEmail: "amina.h@email.com",
    customerPhone: "+254 722 456 789",
    vendorId: "V-2028",
    vendorName: "Zuri Spa & Wellness",
    vendorOwner: "Fatima Osman",
    rating: 5,
    reviewText: "Heaven on earth! The deep tissue massage was exactly what I needed. The therapists are highly skilled and the atmosphere is so relaxing.",
    date: "2025-11-21",
    time: "1:00 PM",
    bookingId: "BK-156",
    service: "Deep Tissue Massage",
    status: "Visible",
    helpful: 42,
    notHelpful: 0,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-21", time: "1:00 PM", by: "Amina Hassan" }],
  },
  {
    id: "REV-006",
    customerId: "C-2024-044",
    customerName: "John Kamau",
    customerEmail: "john.k@email.com",
    customerPhone: "+254 733 567 890",
    vendorId: "V-2029",
    vendorName: "Tech Fix Kenya",
    vendorOwner: "Peter Wanjiru",
    rating: 3,
    reviewText: "Service was okay. They fixed my laptop but it took longer than promised. Price was fair though.",
    date: "2025-11-20",
    time: "3:45 PM",
    bookingId: "BK-178",
    service: "Laptop Repair",
    status: "Visible",
    helpful: 12,
    notHelpful: 3,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-20", time: "3:45 PM", by: "John Kamau" }],
  },
  {
    id: "REV-007",
    customerId: "C-2024-056",
    customerName: "Blessing Nwosu",
    customerEmail: "blessing.n@email.com",
    customerPhone: "+234 805 678 9012",
    vendorId: "V-2030",
    vendorName: "Afro Glam Photography",
    vendorOwner: "Tunde Bakare",
    rating: 5,
    reviewText: "Tunde captured our wedding perfectly! Every moment was beautifully documented. The photos are stunning and we couldn't be happier!",
    date: "2025-11-19",
    time: "7:30 PM",
    bookingId: "BK-203",
    service: "Wedding Photography",
    status: "Visible",
    helpful: 67,
    notHelpful: 1,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-19", time: "7:30 PM", by: "Blessing Nwosu" }],
  },
  {
    id: "REV-008",
    customerId: "C-2024-067",
    customerName: "Ahmed Ibrahim",
    customerEmail: "ahmed.i@email.com",
    customerPhone: "+234 806 789 0123",
    vendorId: "V-2031",
    vendorName: "Lagos Auto Detailing",
    vendorOwner: "Emeka Obi",
    rating: 4,
    reviewText: "Great attention to detail! My car looks brand new. Would give 5 stars if they offered evening appointments.",
    date: "2025-11-18",
    time: "11:20 AM",
    bookingId: "BK-234",
    service: "Full Car Detailing",
    status: "Visible",
    helpful: 19,
    notHelpful: 2,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-18", time: "11:20 AM", by: "Ahmed Ibrahim" }],
  },
  {
    id: "REV-009",
    customerId: "C-2024-078",
    customerName: "Chinwe Okoro",
    customerEmail: "chinwe.o@email.com",
    customerPhone: "+234 807 890 1234",
    vendorId: "V-2032",
    vendorName: "Little Scholars Tutoring",
    vendorOwner: "Dr. Ngozi Eze",
    rating: 5,
    reviewText: "My daughter's grades improved significantly after just one month! The tutors are patient, knowledgeable, and truly care about the students.",
    date: "2025-11-17",
    time: "5:00 PM",
    bookingId: "BK-267",
    service: "Math Tutoring",
    status: "Visible",
    helpful: 28,
    notHelpful: 0,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-17", time: "5:00 PM", by: "Chinwe Okoro" }],
  },
  {
    id: "REV-010",
    customerId: "C-2024-089",
    customerName: "Mohammed Ali",
    customerEmail: "mohammed.a@email.com",
    customerPhone: "+254 744 901 234",
    vendorId: "V-2033",
    vendorName: "Nairobi Movers Pro",
    vendorOwner: "James Otieno",
    rating: 1,
    reviewText: "Terrible experience! They damaged my furniture and were very unprofessional. Customer service was unhelpful.",
    date: "2025-11-16",
    time: "8:45 AM",
    bookingId: "BK-289",
    service: "Home Moving Service",
    status: "Visible",
    helpful: 5,
    notHelpful: 2,
    flagged: true,
    adminNotes: "Flagged by vendor for review. Investigation pending.",
    history: [
      { action: "Review Posted", date: "2025-11-16", time: "8:45 AM", by: "Mohammed Ali" },
      { action: "Review Flagged", date: "2025-11-17", time: "10:00 AM", by: "Vendor" },
    ],
  },
  {
    id: "REV-011",
    customerId: "C-2024-092",
    customerName: "Esther Wambui",
    customerEmail: "esther.w@email.com",
    customerPhone: "+254 755 012 345",
    vendorId: "V-2024",
    vendorName: "Ubuntu Beauty Lounge",
    vendorOwner: "Amara Johnson",
    rating: 5,
    reviewText: "Love my new locs! Amara and her team are so talented. The salon is clean, welcoming, and the vibes are immaculate!",
    date: "2025-11-15",
    time: "4:15 PM",
    bookingId: "BK-312",
    service: "Locs Installation",
    status: "Visible",
    helpful: 35,
    notHelpful: 0,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-15", time: "4:15 PM", by: "Esther Wambui" }],
  },
  {
    id: "REV-012",
    customerId: "C-2024-103",
    customerName: "Daniel Osei",
    customerEmail: "daniel.o@email.com",
    customerPhone: "+233 244 123 456",
    vendorId: "V-2034",
    vendorName: "Accra Fitness Studio",
    vendorOwner: "Kwame Mensah",
    rating: 4,
    reviewText: "Great gym with modern equipment. The trainers are knowledgeable. Only downside is it can get crowded during peak hours.",
    date: "2025-11-14",
    time: "7:00 AM",
    bookingId: "BK-345",
    service: "Personal Training Session",
    status: "Visible",
    helpful: 22,
    notHelpful: 4,
    flagged: false,
    adminNotes: "",
    history: [{ action: "Review Posted", date: "2025-11-14", time: "7:00 AM", by: "Daniel Osei" }],
  },
]
