export type PaymentTransactionStatus = "Completed" | "Pending" | "Refunded" | "Failed"
export type PaymentTransactionType = "Payment" | "Refund"
export type PaymentMethod = "Online" | "Wallet" | "Venue"

export interface PaymentTransaction {
  id: string
  transactionRef: string
  bookingRef: string
  type: PaymentTransactionType
  customerName: string
  customerId: string
  customerEmail: string
  vendorName: string
  vendorId: string
  vendorEmail: string
  amount: number
  platformFee: number
  vendorAmount: number
  paymentMethod: PaymentMethod
  paymentProvider: string
  status: PaymentTransactionStatus
  date: string
  time: string
  description: string
}

export type WalletTransactionType = "Top-up" | "Credit" | "Debit" | "Withdrawal"
export type WalletUserType = "Customer" | "Vendor"

export interface WalletTransaction {
  id: string
  transactionRef: string
  userId: string
  userName: string
  userType: WalletUserType
  type: WalletTransactionType
  amount: number
  balanceBefore: number
  balanceAfter: number
  method: string
  status: PaymentTransactionStatus
  date: string
  time: string
  description: string
  linkedTransaction?: string
}

export const initialPaymentTransactions: PaymentTransaction[] = [
  {
    id: "TXN001",
    transactionRef: "AFV-PAY-001",
    bookingRef: "AFV-BK-001",
    type: "Payment",
    customerName: "Amara Okafor",
    customerId: "CUST001",
    customerEmail: "amara@gmail.com",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    amount: 120,
    platformFee: 12,
    vendorAmount: 108,
    paymentMethod: "Online",
    paymentProvider: "Stripe",
    status: "Completed",
    date: "2025-11-15",
    time: "10:30 AM",
    description: "Payment for Box Braids service",
  },
  {
    id: "TXN002",
    transactionRef: "AFV-PAY-002",
    bookingRef: "AFV-BK-002",
    type: "Payment",
    customerName: "Fatima Bello",
    customerId: "CUST003",
    customerEmail: "fatima.bello@email.com",
    vendorName: "Chef Aisha's Kitchen",
    vendorId: "V-2026",
    vendorEmail: "chef@aisha.ng",
    amount: 2500,
    platformFee: 250,
    vendorAmount: 2250,
    paymentMethod: "Online",
    paymentProvider: "Paystack",
    status: "Completed",
    date: "2025-09-20",
    time: "2:15 PM",
    description: "Payment for Wedding Catering service",
  },
  {
    id: "TXN003",
    transactionRef: "AFV-PAY-003",
    bookingRef: "AFV-BK-003",
    type: "Payment",
    customerName: "Chidi Nwankwo",
    customerId: "CUST002",
    customerEmail: "chidi.nwankwo@email.com",
    vendorName: "Fade District",
    vendorId: "V-2027",
    vendorEmail: "info@fadedistrict.ng",
    amount: 150,
    platformFee: 15,
    vendorAmount: 135,
    paymentMethod: "Wallet",
    paymentProvider: "Afrivendor Wallet",
    status: "Completed",
    date: "2025-11-08",
    time: "3:45 PM",
    description: "Payment for Haircut & Shave service",
  },
  {
    id: "TXN004",
    transactionRef: "AFV-PAY-004",
    bookingRef: "AFV-BK-006",
    type: "Payment",
    customerName: "Thabo Ndlovu",
    customerId: "CUST011",
    customerEmail: "thabo.ndlovu@email.com",
    vendorName: "Joburg Barber Co",
    vendorId: "V-2030",
    vendorEmail: "info@joburgbarber.co.za",
    amount: 220,
    platformFee: 22,
    vendorAmount: 198,
    paymentMethod: "Online",
    paymentProvider: "Stripe",
    status: "Pending",
    date: "2025-11-05",
    time: "9:20 AM",
    description: "Payment for Premium Grooming service",
  },
  {
    id: "TXN005",
    transactionRef: "AFV-PAY-005",
    bookingRef: "AFV-BK-007",
    type: "Payment",
    customerName: "Ngozi Eze",
    customerId: "CUST006",
    customerEmail: "ngozi.eze@email.com",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    amount: 300,
    platformFee: 30,
    vendorAmount: 270,
    paymentMethod: "Online",
    paymentProvider: "Paystack",
    status: "Completed",
    date: "2025-10-20",
    time: "8:10 AM",
    description: "Payment for Bridal Makeup service",
  },
  {
    id: "TXN006",
    transactionRef: "AFV-REF-001",
    bookingRef: "AFV-BK-011",
    type: "Refund",
    customerName: "Ebuka Obi",
    customerId: "CUST005",
    customerEmail: "ebuka.obi@email.com",
    vendorName: "Chef Aisha's Kitchen",
    vendorId: "V-2026",
    vendorEmail: "chef@aisha.ng",
    amount: 350,
    platformFee: 35,
    vendorAmount: 315,
    paymentMethod: "Online",
    paymentProvider: "Paystack",
    status: "Refunded",
    date: "2025-06-18",
    time: "11:30 AM",
    description: "Refund for cancelled Meal Prep service",
  },
  {
    id: "TXN007",
    transactionRef: "AFV-PAY-007",
    bookingRef: "AFV-BK-010",
    type: "Payment",
    customerName: "Adaeze Nwosu",
    customerId: "CUST008",
    customerEmail: "adaeze@email.com",
    vendorName: "GlamLuxe Studios",
    vendorId: "V-2032",
    vendorEmail: "info@glamluxe.ng",
    amount: 450,
    platformFee: 45,
    vendorAmount: 405,
    paymentMethod: "Online",
    paymentProvider: "Stripe",
    status: "Completed",
    date: "2025-11-12",
    time: "10:05 AM",
    description: "Payment for Professional Photoshoot service",
  },
  {
    id: "TXN008",
    transactionRef: "AFV-PAY-008",
    bookingRef: "AFV-BK-012",
    type: "Payment",
    customerName: "Amara Okafor",
    customerId: "CUST001",
    customerEmail: "amara@gmail.com",
    vendorName: "Serengeti Cafe",
    vendorId: "V-2023",
    vendorEmail: "hello@serengeticafe.co.ke",
    amount: 1250,
    platformFee: 125,
    vendorAmount: 1125,
    paymentMethod: "Online",
    paymentProvider: "Stripe",
    status: "Pending",
    date: "2025-11-20",
    time: "5:20 PM",
    description: "Payment for Private Event Catering service",
  },
  {
    id: "TXN009",
    transactionRef: "AFV-PAY-009",
    bookingRef: "AFV-BK-004",
    type: "Payment",
    customerName: "Kwame Mensah",
    customerId: "CUST009",
    customerEmail: "kwame.mensah@email.com",
    vendorName: "Accra Grill House",
    vendorId: "V-2028",
    vendorEmail: "info@accragrill.gh",
    amount: 180,
    platformFee: 18,
    vendorAmount: 162,
    paymentMethod: "Venue",
    paymentProvider: "Cash",
    status: "Completed",
    date: "2025-09-10",
    time: "7:30 PM",
    description: "Payment for Dinner Reservation",
  },
  {
    id: "TXN010",
    transactionRef: "AFV-PAY-010",
    bookingRef: "AFV-BK-005",
    type: "Payment",
    customerName: "Aisha Kamara",
    customerId: "CUST010",
    customerEmail: "aisha.kamara@email.com",
    vendorName: "Nairobi Hair Studio",
    vendorId: "V-2029",
    vendorEmail: "info@nairobihair.co.ke",
    amount: 320,
    platformFee: 32,
    vendorAmount: 288,
    paymentMethod: "Online",
    paymentProvider: "Paystack",
    status: "Completed",
    date: "2025-10-18",
    time: "11:15 AM",
    description: "Payment for Natural Hair Treatment service",
  },
  {
    id: "TXN011",
    transactionRef: "AFV-PAY-011",
    bookingRef: "AFV-BK-014",
    type: "Payment",
    customerName: "Yemi Adebayo",
    customerId: "CUST013",
    customerEmail: "yemi@email.com",
    vendorName: "Fade District",
    vendorId: "V-2027",
    vendorEmail: "info@fadedistrict.ng",
    amount: 80,
    platformFee: 8,
    vendorAmount: 72,
    paymentMethod: "Venue",
    paymentProvider: "Cash",
    status: "Pending",
    date: "2025-11-26",
    time: "6:15 PM",
    description: "Payment for Beard Trim service",
  },
  {
    id: "TXN012",
    transactionRef: "AFV-PAY-012",
    bookingRef: "AFV-BK-013",
    type: "Payment",
    customerName: "Fatima Bello",
    customerId: "CUST003",
    customerEmail: "fatima.bello@email.com",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    amount: 80,
    platformFee: 8,
    vendorAmount: 72,
    paymentMethod: "Wallet",
    paymentProvider: "Afrivendor Wallet",
    status: "Completed",
    date: "2025-11-22",
    time: "2:30 PM",
    description: "Payment for Cornrows service",
  },
  {
    id: "TXN013",
    transactionRef: "AFV-PAY-013",
    bookingRef: "AFV-BK-017",
    type: "Payment",
    customerName: "Zainab Hassan",
    customerId: "CUST016",
    customerEmail: "zainab@email.com",
    vendorName: "Chef Aisha's Kitchen",
    vendorId: "V-2026",
    vendorEmail: "chef@aisha.ng",
    amount: 1800,
    platformFee: 180,
    vendorAmount: 1620,
    paymentMethod: "Online",
    paymentProvider: "Stripe",
    status: "Pending",
    date: "2025-11-25",
    time: "3:45 PM",
    description: "Payment for Birthday Party Catering service",
  },
  {
    id: "TXN014",
    transactionRef: "AFV-PAY-014",
    bookingRef: "AFV-BK-020",
    type: "Payment",
    customerName: "Tunde Bakare",
    customerId: "CUST019",
    customerEmail: "tunde@email.com",
    vendorName: "Tunde's Tech Repair",
    vendorId: "V-2031",
    vendorEmail: "tunde@techrepair.ng",
    amount: 180,
    platformFee: 18,
    vendorAmount: 162,
    paymentMethod: "Wallet",
    paymentProvider: "Afrivendor Wallet",
    status: "Completed",
    date: "2025-11-24",
    time: "10:20 AM",
    description: "Payment for Laptop Repair service",
  },
  {
    id: "TXN015",
    transactionRef: "AFV-PAY-015",
    bookingRef: "AFV-BK-015",
    type: "Payment",
    customerName: "Chiamaka Onu",
    customerId: "CUST014",
    customerEmail: "chiamaka@email.com",
    vendorName: "Nairobi Hair Studio",
    vendorId: "V-2029",
    vendorEmail: "info@nairobihair.co.ke",
    amount: 250,
    platformFee: 25,
    vendorAmount: 225,
    paymentMethod: "Online",
    paymentProvider: "Paystack",
    status: "Completed",
    date: "2025-09-01",
    time: "9:10 AM",
    description: "Payment for Silk Press service",
  },
]

export const initialWalletTransactions: WalletTransaction[] = [
  {
    id: "WAL001",
    transactionRef: "AFV-WAL-001",
    userId: "CUST001",
    userName: "Amara Okafor",
    userType: "Customer",
    type: "Top-up",
    amount: 500,
    balanceBefore: 0,
    balanceAfter: 500,
    method: "Bank Transfer",
    status: "Completed",
    date: "2025-11-10",
    time: "9:30 AM",
    description: "Wallet top-up via bank transfer",
  },
  {
    id: "WAL002",
    transactionRef: "AFV-WAL-002",
    userId: "CUST001",
    userName: "Amara Okafor",
    userType: "Customer",
    type: "Debit",
    amount: 50,
    balanceBefore: 500,
    balanceAfter: 450,
    method: "Wallet Payment",
    status: "Completed",
    date: "2025-11-15",
    time: "10:30 AM",
    description: "Payment deducted for booking AFV-BK-001",
    linkedTransaction: "TXN001",
  },
  {
    id: "WAL003",
    transactionRef: "AFV-WAL-003",
    userId: "CUST003",
    userName: "Fatima Bello",
    userType: "Customer",
    type: "Top-up",
    amount: 1000,
    balanceBefore: 0,
    balanceAfter: 1000,
    method: "Card",
    status: "Completed",
    date: "2025-11-05",
    time: "2:15 PM",
    description: "Wallet top-up via credit card",
  },
  {
    id: "WAL004",
    transactionRef: "AFV-WAL-004",
    userId: "CUST003",
    userName: "Fatima Bello",
    userType: "Customer",
    type: "Debit",
    amount: 250,
    balanceBefore: 1000,
    balanceAfter: 750,
    method: "Wallet Payment",
    status: "Completed",
    date: "2025-11-22",
    time: "2:30 PM",
    description: "Payment deducted for booking AFV-BK-013",
    linkedTransaction: "TXN012",
  },
  {
    id: "WAL005",
    transactionRef: "AFV-WAL-005",
    userId: "V-2024",
    userName: "Ubuntu Beauty Lounge",
    userType: "Vendor",
    type: "Credit",
    amount: 108,
    balanceBefore: 2840,
    balanceAfter: 2948,
    method: "Service Payment",
    status: "Completed",
    date: "2025-11-15",
    time: "10:35 AM",
    description: "Payment received for booking AFV-BK-001",
    linkedTransaction: "TXN001",
  },
  {
    id: "WAL006",
    transactionRef: "AFV-WAL-006",
    userId: "V-2024",
    userName: "Ubuntu Beauty Lounge",
    userType: "Vendor",
    type: "Withdrawal",
    amount: 2000,
    balanceBefore: 2948,
    balanceAfter: 948,
    method: "Bank Transfer",
    status: "Completed",
    date: "2025-11-18",
    time: "3:20 PM",
    description: "Withdrawal to bank account ****5678",
  },
  {
    id: "WAL007",
    transactionRef: "AFV-WAL-007",
    userId: "CUST002",
    userName: "Chidi Nwankwo",
    userType: "Customer",
    type: "Top-up",
    amount: 300,
    balanceBefore: 50,
    balanceAfter: 350,
    method: "Mobile Money",
    status: "Completed",
    date: "2025-11-07",
    time: "11:45 AM",
    description: "Wallet top-up via mobile money",
  },
  {
    id: "WAL008",
    transactionRef: "AFV-WAL-008",
    userId: "CUST002",
    userName: "Chidi Nwankwo",
    userType: "Customer",
    type: "Debit",
    amount: 150,
    balanceBefore: 350,
    balanceAfter: 200,
    method: "Wallet Payment",
    status: "Completed",
    date: "2025-11-08",
    time: "3:45 PM",
    description: "Payment deducted for booking AFV-BK-003",
    linkedTransaction: "TXN003",
  },
  {
    id: "WAL009",
    transactionRef: "AFV-WAL-009",
    userId: "V-2026",
    userName: "Chef Aisha's Kitchen",
    userType: "Vendor",
    type: "Credit",
    amount: 2250,
    balanceBefore: 5680,
    balanceAfter: 7930,
    method: "Service Payment",
    status: "Completed",
    date: "2025-09-20",
    time: "2:20 PM",
    description: "Payment received for booking AFV-BK-002",
    linkedTransaction: "TXN002",
  },
  {
    id: "WAL010",
    transactionRef: "AFV-WAL-010",
    userId: "V-2026",
    userName: "Chef Aisha's Kitchen",
    userType: "Vendor",
    type: "Debit",
    amount: 315,
    balanceBefore: 7930,
    balanceAfter: 7615,
    method: "Refund",
    status: "Completed",
    date: "2025-06-18",
    time: "11:35 AM",
    description: "Refund issued for cancelled booking AFV-BK-011",
    linkedTransaction: "TXN006",
  },
  {
    id: "WAL011",
    transactionRef: "AFV-WAL-011",
    userId: "CUST019",
    userName: "Tunde Bakare",
    userType: "Customer",
    type: "Top-up",
    amount: 400,
    balanceBefore: 100,
    balanceAfter: 500,
    method: "Card",
    status: "Completed",
    date: "2025-11-20",
    time: "8:15 AM",
    description: "Wallet top-up via debit card",
  },
  {
    id: "WAL012",
    transactionRef: "AFV-WAL-012",
    userId: "CUST019",
    userName: "Tunde Bakare",
    userType: "Customer",
    type: "Debit",
    amount: 180,
    balanceBefore: 500,
    balanceAfter: 320,
    method: "Wallet Payment",
    status: "Completed",
    date: "2025-11-24",
    time: "10:20 AM",
    description: "Payment deducted for booking AFV-BK-020",
    linkedTransaction: "TXN014",
  },
]
