export type BookingStatus =
  | "Upcoming"
  | "Pending"
  | "Accepted"
  | "In Progress"
  | "Completed"
  | "Cancelled"
  | "Rejected"
export type PaymentStatus = "Paid" | "Pending" | "Refunded" | "Failed"
export type PaymentMethod = "Online" | "Wallet" | "Venue"

export interface Booking {
  id: string
  bookingRef: string
  customerName: string
  customerId: string
  customerEmail: string
  customerPhone: string
  vendorName: string
  vendorId: string
  vendorEmail: string
  service: string
  date: string
  time: string
  duration: number
  amount: number
  status: BookingStatus
  paymentStatus: PaymentStatus
  paymentMethod: PaymentMethod
  location: string
  notes: string
  bookingDate: string
  venueType: string
  /** From admin API when a reschedule was proposed */
  rescheduleDate?: string | null
  rescheduleTime?: string | null
}

export const initialBookings: Booking[] = [
  {
    id: "BK001",
    bookingRef: "AFV-BK-001",
    customerName: "Amara Okafor",
    customerId: "CUST001",
    customerEmail: "amara@gmail.com",
    customerPhone: "+234 801 234 5678",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    service: "Box Braids",
    date: "2025-11-25",
    time: "10:00 AM",
    duration: 240,
    amount: 120,
    status: "Upcoming",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Lagos, Nigeria",
    notes: "Customer prefers medium-sized braids",
    bookingDate: "2025-11-15",
    venueType: "Salon",
  },
  {
    id: "BK002",
    bookingRef: "AFV-BK-002",
    customerName: "Fatima Bello",
    customerId: "CUST003",
    customerEmail: "fatima.bello@email.com",
    customerPhone: "+234 803 456 7890",
    vendorName: "Chef Aisha's Kitchen",
    vendorId: "V-2026",
    vendorEmail: "chef@aisha.ng",
    service: "Wedding Catering",
    date: "2025-10-15",
    time: "2:00 PM",
    duration: 300,
    amount: 2500,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Kano, Nigeria",
    notes: "150 guests, traditional Nigerian menu",
    bookingDate: "2025-09-20",
    venueType: "Event Hall",
  },
  {
    id: "BK003",
    bookingRef: "AFV-BK-003",
    customerName: "Chidi Nwankwo",
    customerId: "CUST002",
    customerEmail: "chidi.nwankwo@email.com",
    customerPhone: "+234 802 345 6789",
    vendorName: "Fade District",
    vendorId: "V-2027",
    vendorEmail: "info@fadedistrict.ng",
    service: "Haircut & Shave",
    date: "2025-11-10",
    time: "3:00 PM",
    duration: 60,
    amount: 150,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Wallet",
    location: "Abuja, Nigeria",
    notes: "",
    bookingDate: "2025-11-08",
    venueType: "Barbershop",
  },
  {
    id: "BK004",
    bookingRef: "AFV-BK-004",
    customerName: "Kwame Mensah",
    customerId: "CUST009",
    customerEmail: "kwame.mensah@email.com",
    customerPhone: "+233 24 567 8901",
    vendorName: "Accra Grill House",
    vendorId: "V-2028",
    vendorEmail: "info@accragrill.gh",
    service: "Dinner Reservation",
    date: "2025-09-15",
    time: "7:00 PM",
    duration: 120,
    amount: 180,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Venue",
    location: "Accra, Ghana",
    notes: "Table for 4 people",
    bookingDate: "2025-09-10",
    venueType: "Restaurant",
  },
  {
    id: "BK005",
    bookingRef: "AFV-BK-005",
    customerName: "Aisha Kamara",
    customerId: "CUST010",
    customerEmail: "aisha.kamara@email.com",
    customerPhone: "+254 712 345 678",
    vendorName: "Nairobi Hair Studio",
    vendorId: "V-2029",
    vendorEmail: "info@nairobihair.co.ke",
    service: "Natural Hair Treatment",
    date: "2025-10-25",
    time: "11:00 AM",
    duration: 180,
    amount: 320,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Nairobi, Kenya",
    notes: "Deep conditioning treatment requested",
    bookingDate: "2025-10-18",
    venueType: "Salon",
  },
  {
    id: "BK006",
    bookingRef: "AFV-BK-006",
    customerName: "Thabo Ndlovu",
    customerId: "CUST011",
    customerEmail: "thabo.ndlovu@email.com",
    customerPhone: "+27 82 456 7890",
    vendorName: "Joburg Barber Co",
    vendorId: "V-2030",
    vendorEmail: "info@joburgbarber.co.za",
    service: "Premium Grooming",
    date: "2025-11-12",
    time: "9:00 AM",
    duration: 90,
    amount: 220,
    status: "Upcoming",
    paymentStatus: "Pending",
    paymentMethod: "Online",
    location: "Johannesburg, South Africa",
    notes: "",
    bookingDate: "2025-11-05",
    venueType: "Barbershop",
  },
  {
    id: "BK007",
    bookingRef: "AFV-BK-007",
    customerName: "Ngozi Eze",
    customerId: "CUST006",
    customerEmail: "ngozi.eze@email.com",
    customerPhone: "+234 806 789 0123",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    service: "Bridal Makeup",
    date: "2025-11-02",
    time: "8:00 AM",
    duration: 150,
    amount: 300,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Lagos, Nigeria",
    notes: "Wedding at 12pm, makeup should be ready by 11am",
    bookingDate: "2025-10-20",
    venueType: "Salon",
  },
  {
    id: "BK008",
    bookingRef: "AFV-BK-008",
    customerName: "Adeola Williams",
    customerId: "CUST004",
    customerEmail: "adeola.w@email.com",
    customerPhone: "+234 804 567 8901",
    vendorName: "Tunde's Tech Repair",
    vendorId: "V-2031",
    vendorEmail: "tunde@techrepair.ng",
    service: "IT Consulting",
    date: "2025-08-20",
    time: "1:00 PM",
    duration: 120,
    amount: 550,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Ibadan, Nigeria",
    notes: "Network setup for small office",
    bookingDate: "2025-08-15",
    venueType: "Customer Location",
  },
  {
    id: "BK009",
    bookingRef: "AFV-BK-009",
    customerName: "Ibrahim Musa",
    customerId: "CUST007",
    customerEmail: "ibrahim.musa@email.com",
    customerPhone: "+234 807 890 1234",
    vendorName: "Fade District",
    vendorId: "V-2027",
    vendorEmail: "info@fadedistrict.ng",
    service: "Premium Haircut",
    date: "2025-11-18",
    time: "4:00 PM",
    duration: 45,
    amount: 120,
    status: "Upcoming",
    paymentStatus: "Paid",
    paymentMethod: "Wallet",
    location: "Abuja, Nigeria",
    notes: "",
    bookingDate: "2025-11-10",
    venueType: "Barbershop",
  },
  {
    id: "BK010",
    bookingRef: "AFV-BK-010",
    customerName: "Adaeze Nwosu",
    customerId: "CUST008",
    customerEmail: "adaeze@email.com",
    customerPhone: "+234 808 901 2345",
    vendorName: "GlamLuxe Studios",
    vendorId: "V-2032",
    vendorEmail: "info@glamluxe.ng",
    service: "Professional Photoshoot",
    date: "2025-11-20",
    time: "10:00 AM",
    duration: 120,
    amount: 450,
    status: "Upcoming",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Lagos, Nigeria",
    notes: "Portfolio photoshoot - outdoor setting preferred",
    bookingDate: "2025-11-12",
    venueType: "Studio",
  },
  {
    id: "BK011",
    bookingRef: "AFV-BK-011",
    customerName: "Ebuka Obi",
    customerId: "CUST005",
    customerEmail: "ebuka.obi@email.com",
    customerPhone: "+234 805 678 9012",
    vendorName: "Chef Aisha's Kitchen",
    vendorId: "V-2026",
    vendorEmail: "chef@aisha.ng",
    service: "Meal Prep",
    date: "2025-06-20",
    time: "12:00 PM",
    duration: 90,
    amount: 350,
    status: "Cancelled",
    paymentStatus: "Refunded",
    paymentMethod: "Online",
    location: "Port Harcourt, Nigeria",
    notes: "",
    bookingDate: "2025-06-15",
    venueType: "Customer Location",
  },
  {
    id: "BK012",
    bookingRef: "AFV-BK-012",
    customerName: "Amara Okafor",
    customerId: "CUST001",
    customerEmail: "amara@gmail.com",
    customerPhone: "+234 801 234 5678",
    vendorName: "Serengeti Cafe",
    vendorId: "V-2023",
    vendorEmail: "hello@serengeticafe.co.ke",
    service: "Private Event Catering",
    date: "2025-12-05",
    time: "5:00 PM",
    duration: 180,
    amount: 1250,
    status: "Upcoming",
    paymentStatus: "Pending",
    paymentMethod: "Online",
    location: "Lagos, Nigeria",
    notes: "Corporate dinner for 30 people",
    bookingDate: "2025-11-20",
    venueType: "Event Hall",
  },
  {
    id: "BK013",
    bookingRef: "AFV-BK-013",
    customerName: "Fatima Bello",
    customerId: "CUST003",
    customerEmail: "fatima.bello@email.com",
    customerPhone: "+234 803 456 7890",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    service: "Cornrows",
    date: "2025-11-30",
    time: "2:00 PM",
    duration: 150,
    amount: 80,
    status: "Upcoming",
    paymentStatus: "Paid",
    paymentMethod: "Wallet",
    location: "Kano, Nigeria",
    notes: "",
    bookingDate: "2025-11-22",
    venueType: "Salon",
  },
  {
    id: "BK014",
    bookingRef: "AFV-BK-014",
    customerName: "Yemi Adebayo",
    customerId: "CUST013",
    customerEmail: "yemi@email.com",
    customerPhone: "+234 809 012 3456",
    vendorName: "Fade District",
    vendorId: "V-2027",
    vendorEmail: "info@fadedistrict.ng",
    service: "Beard Trim",
    date: "2025-11-28",
    time: "6:00 PM",
    duration: 30,
    amount: 80,
    status: "Upcoming",
    paymentStatus: "Pending",
    paymentMethod: "Venue",
    location: "Lagos, Nigeria",
    notes: "",
    bookingDate: "2025-11-26",
    venueType: "Barbershop",
  },
  {
    id: "BK015",
    bookingRef: "AFV-BK-015",
    customerName: "Chiamaka Onu",
    customerId: "CUST014",
    customerEmail: "chiamaka@email.com",
    customerPhone: "+234 810 123 4567",
    vendorName: "Nairobi Hair Studio",
    vendorId: "V-2029",
    vendorEmail: "info@nairobihair.co.ke",
    service: "Silk Press",
    date: "2025-09-08",
    time: "9:00 AM",
    duration: 120,
    amount: 250,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Nairobi, Kenya",
    notes: "Heat protectant required",
    bookingDate: "2025-09-01",
    venueType: "Salon",
  },
  {
    id: "BK016",
    bookingRef: "AFV-BK-016",
    customerName: "Oluwaseun Balogun",
    customerId: "CUST015",
    customerEmail: "seun@email.com",
    customerPhone: "+234 811 234 5678",
    vendorName: "Joburg Barber Co",
    vendorId: "V-2030",
    vendorEmail: "info@joburgbarber.co.za",
    service: "Haircut",
    date: "2025-08-12",
    time: "11:00 AM",
    duration: 45,
    amount: 150,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Venue",
    location: "Johannesburg, South Africa",
    notes: "",
    bookingDate: "2025-08-10",
    venueType: "Barbershop",
  },
  {
    id: "BK017",
    bookingRef: "AFV-BK-017",
    customerName: "Zainab Hassan",
    customerId: "CUST016",
    customerEmail: "zainab@email.com",
    customerPhone: "+234 812 345 6789",
    vendorName: "Chef Aisha's Kitchen",
    vendorId: "V-2026",
    vendorEmail: "chef@aisha.ng",
    service: "Birthday Party Catering",
    date: "2025-12-10",
    time: "3:00 PM",
    duration: 240,
    amount: 1800,
    status: "Upcoming",
    paymentStatus: "Pending",
    paymentMethod: "Online",
    location: "Kano, Nigeria",
    notes: "50 guests, kid-friendly menu",
    bookingDate: "2025-11-25",
    venueType: "Customer Location",
  },
  {
    id: "BK018",
    bookingRef: "AFV-BK-018",
    customerName: "Kofi Asante",
    customerId: "CUST017",
    customerEmail: "kofi@email.com",
    customerPhone: "+233 25 678 9012",
    vendorName: "Accra Grill House",
    vendorId: "V-2028",
    vendorEmail: "info@accragrill.gh",
    service: "Lunch Buffet",
    date: "2025-10-30",
    time: "12:00 PM",
    duration: 90,
    amount: 95,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Venue",
    location: "Accra, Ghana",
    notes: "",
    bookingDate: "2025-10-28",
    venueType: "Restaurant",
  },
  {
    id: "BK019",
    bookingRef: "AFV-BK-019",
    customerName: "Mariam Diop",
    customerId: "CUST018",
    customerEmail: "mariam@email.com",
    customerPhone: "+221 77 123 4567",
    vendorName: "Ubuntu Beauty Lounge",
    vendorId: "V-2024",
    vendorEmail: "info@ubuntubeauty.ng",
    service: "Twists",
    date: "2025-11-15",
    time: "1:00 PM",
    duration: 180,
    amount: 95,
    status: "Completed",
    paymentStatus: "Paid",
    paymentMethod: "Online",
    location: "Lagos, Nigeria",
    notes: "Medium-length twists",
    bookingDate: "2025-11-08",
    venueType: "Salon",
  },
  {
    id: "BK020",
    bookingRef: "AFV-BK-020",
    customerName: "Tunde Bakare",
    customerId: "CUST019",
    customerEmail: "tunde@email.com",
    customerPhone: "+234 813 456 7890",
    vendorName: "Tunde's Tech Repair",
    vendorId: "V-2031",
    vendorEmail: "tunde@techrepair.ng",
    service: "Laptop Repair",
    date: "2025-11-29",
    time: "10:00 AM",
    duration: 60,
    amount: 180,
    status: "Upcoming",
    paymentStatus: "Paid",
    paymentMethod: "Wallet",
    location: "Ibadan, Nigeria",
    notes: "Screen replacement needed",
    bookingDate: "2025-11-24",
    venueType: "Shop",
  },
]
